Updated bids test to check all files
NDCLab/baseEEG pull request #94
Opened 2021-05-10 16:44 UTC by F-said

- swapped BIDSPath for os to get all metadata and data into testing
    - invalid files in now fail correctly:
    ```
    self.assertTrue(self.validator.is_bids(file[4:]),
    AssertionError: False is not true : 
    BIDS validate failed on file\sub-NDARAB793GL3\ses-01\eeg\sub-NDARAB793GL3-testfail.json
    ```
    
Going off on what @yanbin-niu observed in #25, it looks like EEGLab's bid validator fails for some contents of the meta-data. While this merge checks the validity of the BIDS path format, perhaps another package like [bids-standard/bids-validator](https://github.com/bids-standard/bids-validator) could be added on for the next iteration of this feature to check for internal errors.

2021-05-11 04:59 UTC, yanbin-niu commented
Hi, @F-said . Just curious about `validator.is_bids`. It seems that it just checks the extension of a file, correct? is it able to do any other checking? Can it receive a path to check the whole structure of BIDS folder?

2021-05-13 02:12 UTC, DMRoberts commented on base_eeg/bids_test.py
> +from os import walk
```suggestion
from os import walk, sep
```

2021-05-13 02:27 UTC, DMRoberts requested changes
Looks good @F-said , I made a couple of suggested edits to the file which are in a gist here: https://gist.github.com/DMRoberts/1a106c09acc3ce11109be2607f4e589f

I was originally going to use the code 'suggestion' feature as part of the review but it seemed a bit complex for multiple edits.

The edits are to:
1) Strip off the dataset root regardless of root name. In the current version I believe the first 4 characters are stripped since the dataset is named 'BIDS'.  However I believe a BIDS formatted dataset can be called anything, we just happened to name ours 'BIDS'.

2) Iterate through the file test loop in subTests. This just iterates through all the tests and then returns the passing / failing tests at the end of the loop. I believe without subTests all files tests are part of the same overall test, so it will return as failing after the first failed test is encountered and won't test the others.

2021-05-13 02:40 UTC, DMRoberts commented
@yanbin-niu @F-said I had originally thought that the bids-validator Python package would do everything that the Javascript version does since it's part of the same project, but it does look like it is just checking for filename validation as you both mentioned.

Interestingly I just tried our BIDS dataset with the web Javascript validator, and there is 1 error, related to a missing value in participants.tsv. I'll take a look at that, but it's strange it isn't catching the error that @yanbin-niu found is generated by EEGLAB when the BIDS dataset is loaded, related to the format of the timestamp in *scans.tsv ( https://github.com/NDCLab/baseEEG/issues/25#issuecomment-833462228 ). Maybe EEGLAB is wrong there, or the BIDS web validator isn't complete.

2021-05-13 08:37 UTC, F-said commented
@DMRoberts thanks for the review, will re-request review once edits are incorporated.

2021-05-13 08:43 UTC, F-said commented
@yanbin-niu @DMRoberts 
Looking more into the bids-validator, it looks like future development will likewise be focused on refactoring the validator [solely in JavaScript](https://github.com/bids-standard/bids-validator/issues/1277). Maybe this test would be better to re-write in JS?

In regards to the timestamp error caught by EEGLAB, I think this is a bug in the EEGLAB bids validator:

The bids-EEG [docs](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html) state:

> Note that the date and time information SHOULD be stored in the Study key file ([scans.tsv](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#scans-file)). Date time information MUST be expressed as indicated in [Units](https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#units)

The [common principles doc](https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#units) that describes the units then states:
> Date time information MUST be expressed in the following format YYYY-MM-DDThh:mm:ss[.000000][Z] (year, month, day, hour (24h), minute, second, optional fractional seconds, and optional UTC time indicator).

So while the addition of fractional seconds is optional, it's still valid.

2021-05-14 01:43 UTC, DMRoberts approved these changes
Looks good!

2021-05-14 13:06 UTC, georgebuzzell commented
Thank you @DavyNeat and @F-said ! I am margining this, given dan's approval.

2021-05-14 13:06 UTC, merged